//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityAnnouncement
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long CommunityId { get; set; }
        public long CreatorId { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual User User { get; set; }
    }
}
