//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offert
    {
        public long Id { get; set; }
        public System.DateTime ProposedReturn { get; set; }
        public string Comment { get; set; }
        public int State { get; set; }
        public Nullable<long> SenderId { get; set; }
        public Nullable<long> ReceiverId { get; set; }
        public Nullable<long> SenderToolId { get; set; }
        public Nullable<long> ReceiverToolId { get; set; }
    
        public virtual Tool Tool { get; set; }
        public virtual Tool Tool1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
