//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolPicture
    {
        public long Id { get; set; }
        public byte[] PictureData { get; set; }
        public long ToolId { get; set; }
    
        public virtual Tool Tool { get; set; }
    }
}
