//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long Id { get; set; }
        public bool IsFinished { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public string StartLocation { get; set; }
        public string FinishLocation { get; set; }
        public int ToolState { get; set; }
        public string LenderComment { get; set; }
        public int LenderOpinion { get; set; }
        public string BorrowerComment { get; set; }
        public int BorrowerOpinion { get; set; }
        public Nullable<long> LenderId { get; set; }
        public Nullable<long> BorowerId { get; set; }
        public Nullable<long> LenderToolId { get; set; }
        public Nullable<long> BorowerToolId { get; set; }
    
        public virtual Tool Tool { get; set; }
        public virtual Tool Tool1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
